project:
  type: book
  output-dir: _book

book:
  title: "A Sample ITU Thesis Title"
  author: "Student Name SURNAME"
  chapters:
    - index.qmd
    - Chapters/Chapter2.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd

lang: tr
bibliography: references.bib
suppress-bibliography: true

execute:
  echo: false
  warning: false

itu-thesis:
  author:
    given: "Student Name"
    family: "SURNAME"
    title: ""
  student-id: "123456789"
  title-tr:
    line-1: "ITU QUARTO TEZ SABLONU"
    line-2: "GEREKIRSE IKINCI SATIR"
    line-3: ""
  title-en:
    line-1: "ITU QUARTO THESIS TEMPLATE"
    line-2: "SECOND LINE IF NEEDED"
    line-3: ""
  department:
    tr: "Inşaat Mühendisliği Anabilim Dalı"
    en: "Department of Civil Engineering"
  program:
    tr: "Yapı Mühendisliği Programı"
    en: "Structure Engineering Programme"
  defense-month:
    tr: "OCAK 2026"
    en: "JANUARY 2026"
  defense-month-lower:
    tr: "Ocak 2026"
    en: "January 2026"
  submission-date:
    tr: "22 Ocak 2026"
    en: "22 January 2026"
  defense-date:
    tr: "29 Ocak 2026"
    en: "29 January 2026"
  advisor:
    name-tr: "Prof. Dr. Advisor NAME"
    affiliation-tr: "İstanbul Teknik Üniversitesi"
    name-en: "Prof. Dr. Advisor NAME"
    affiliation-en: "Istanbul Technical University"
  coadvisor:
    name-tr: ""
    affiliation-tr: ""
    name-en: ""
    affiliation-en: ""
  committee:
    member-1:
      name: "Prof. Dr. Committee MEMBER"
      affiliation: "İstanbul Teknik Üniversitesi"
    member-2:
      name: "Prof. Dr. Committee MEMBER"
      affiliation: "Boğaziçi Üniversitesi"
    member-3:
      name: "Prof. Dr. Committee MEMBER"
      affiliation: "Yıldız Teknik Üniversitesi"
    member-4:
      name: ""
      affiliation: ""
    member-5:
      name: ""
      affiliation: ""
  dedication: ""
  foreword: "Frontmatter/foreword.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  abstract-tr: "Frontmatter/abstract-tr.tex"
  abstract-en: "Frontmatter/abstract-en.tex"
  cv: "Frontmatter/cv.tex"

format:
  itu-thesis-pdf:
    classoption:
      - onluarkali
      - turkce
      - yukseklisans
      - bez
      - LisansustuEgitim
